/*==========================================================================
This file define all the function need to control the light.
	set_led()
	show_seq()
	LED_RGB_Loop()
	
	LED_Game_start()
	LED_Game_continue()
	LED_Game_over()
==========================================================================*/

#include "led_control.h"
#include "Broad.h"


/// @brief function to control LEDs buy uint16 data
/// @param PWM_Red 
/// @param PWM_Green 
/// @param PWM_Blue 
void set_led(uint16_t PWM_Red, uint16_t PWM_Green, uint16_t PWM_Blue)
{
	RED_LED_SetRatio16(RED_LED_DeviceData, PWM_Red);
	GREEN_LED_SetRatio16(GREEN_LED_DeviceData, PWM_Green);
	BLUE_LED_SetRatio16(BLUE_LED_DeviceData, PWM_Blue);
}


/// @brief the function will light the LED with the sequence inputed
/// @param round 			the length of the whole available sequence
/// @param sequence 		the sequence array
/// @param white_region 	where do white light start
/// @param white_length 	the length of white region
/// @param white_enable 	show white light or normal sequence
void show_seq(int round, int sequence[], int white_region, int white_length,int white_enable)
{
    int i;
    for(i=1;i<=round;i++)
		{
            if(white_enable==1 && i>=white_region && i<=white_region+white_length){set_led(0x3A98,0x7530,0xAFC8);}       	//show white
		    else if(sequence[i]==1){set_led(PWM_MAX,PWM_OFF,PWM_OFF);}                              	                    //show red
		    else if(sequence[i]==2){set_led(PWM_OFF,PWM_MAX,PWM_OFF);}                              	                    //show green
		    else if(sequence[i]==3){set_led(PWM_OFF,PWM_OFF,PWM_MAX);}                              	                    //show blue
		    wait(1000);
		    set_led(PWM_OFF,PWM_OFF,PWM_OFF);
		    wait(1000);
		}
}



/// @brief function to generate a RGB Loop
/// @return a noise generated by the user, used in seed of random.

int LED_RGB_Loop()
{
    //define a array to store:[PWM of LED, change direction of the PWM, LED code]
    int16_t red_rgb[3] = {PWM_MAX, -1, 1};
    int16_t green_rgb[3] = {PWM_OFF, 1, 2};
    int16_t blue_rgb[3] = {PWM_OFF, 1, 3};
    uint16_t *p = blue_rgb; //define a pointer to point at which LED in undercontrol

    //init the RGB sequence
    set_led(0,0,0);
    wait(10);
    TSS1_Configure();
    ispressed = 0;
	while(ispressed < 2 )
	{
        TSS_Task();
		set_led(red_rgb[0], green_rgb[0], blue_rgb[0]);
	    // update pwm
	    *p+=*(p+1)*200;							// update the PWM of a LED using the changing rate
	    if(*p==0x0000||*p==PWM_MAX)				// Check if the control of one LED is finished
	    {
	    	*(p+1)=-*(p+1);						// modifie the change rate of one LED
	    	if(*(p+2)==1){p = green_rgb;}		// change the pointer to the next LED
	    	else if(*(p+2)==2){p = blue_rgb;}
	    	else if(*(p+2)==3){p = red_rgb;}
	    }
	    // set pwm
        wait(10);
	}
    ispressed = 0;
	set_led(PWM_OFF, PWM_OFF, PWM_OFF);
    wait(500);
	return (red_rgb[0]+green_rgb[0]+blue_rgb[0]);	// exit RGB, return a noise generated by user.
}

// three function to control light effect/

void LED_Game_start()
{
	set_led(PWM_MAX,PWM_MAX,PWM_MAX);
	wait(2000);
	set_led(PWM_OFF,PWM_OFF,PWM_OFF);
	wait(2000);
}


void LED_Game_continue()
{
    set_led(0x61A8,0x61A8,PWM_OFF);
    wait(1500);
	set_led(PWM_OFF,PWM_OFF,PWM_OFF);
	wait(1500);
}


void LED_Game_over()
{
    int i;
    for(i=0;i<6;i++)
    {
        set_led(PWM_MAX,PWM_MAX,PWM_MAX);
	    wait(200);
	    set_led(PWM_OFF,PWM_OFF,PWM_OFF);
	    wait(200);
    }
}



